### ISSUE TITLE
Credit ?

### ISSUE THREAD

**Issue by ThatCatGuy** [OverlordAkise/darkrp-addons#1]
I made this addon originally and a little credit for it would be nice...  https://steamcommunity.com/sharedfiles/filedetails/?id=2195413561 other than that good work...

**Comment by OverlordAkise** [comment]
Oh, i didn't know you uploaded it on the steam workshop - im really sorry!
Want me to remove mine or add credit everywhere? Im fine with both!

**Comment by ThatCatGuy** [comment]
Just add credit..  Where did you get it from you add to github if you didnt know it was on steam.. ?

**Comment by OverlordAkise** [comment]
I added credit in every file.
Someone wanted me to recreate the addon from a server he played on and I guess they didn't know it was just a workshop addon.
If you ever want me to remove it just tell me :)

**Comment by ThatCatGuy** [comment]
thank you.

**Comment by ThatCatGuy** [comment]
can you change the name to ThatCatGuy :)  dont use that older name anymore..

**Comment by OverlordAkise** [comment]
Done! :)

**Comment by ThatCatGuy** [comment]
thank you and good work on it..
