### ISSUE TITLE
SQL inserts

### ISSUE THREAD

**Issue by Jindego** [OverlordAkise/darkrp-addons#2]
Hi - where do you define the sql database?

[luctus_char] ERROR DURING SQL INSERT IN CREATEPROFILE
no such table: luctus_char

**Comment by OverlordAkise** [comment]
Hi,

The table for the database should automatically be defined, see:

https://github.com/OverlordAkise/darkrp-addons/blob/64e68013bdbbe28f6d8c3c3517872e07ef9ed232/luctus_char/lua/charsystem/sv_main.lua#L13-L15

If you want to use this outside of DarkRP, or for whatever reason it doesn't work for you, you can try to replace the string

`DarkRPDBInitialized`

with

`Initialize`

and it should work again.

Please check if it works then

BR
