### ISSUE TITLE
luctus_char error 

### ISSUE THREAD

**Issue by Bozcx** [OverlordAkise/darkrp-addons#5]
```
[luctus_char] addons/luctus_char/lua/autorun/client/cl_luctus_char.lua:288: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. LuctusCharOpenMenu - addons/luctus_char/lua/autorun/client/cl_luctus_char.lua:288
    3. func - addons/luctus_char/lua/autorun/client/cl_luctus_char.lua:20
     4. unknown - lua/includes/extensions/net.lua:38
```
I'm running a fresh install of DarkRP and wanted to check it out and it resulted in that, unless I am being stupid

**Comment by OverlordAkise** [comment]
Line 288 is the following:
`for k,v in pairs(RPExtraTeams) do`

This line loops over your configured DarkRP jobs.
Your error would mean that something didn't load correctly and you had no DarkRP jobs set because of it.
Please check your server console to see if any errors occured during startup
